services:
  # ---------------------------------------------------------------------------
  # Kafka broker (your existing config)
  # ---------------------------------------------------------------------------
  broker:
    image: confluentinc/cp-kafka:7.6.1
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: "cmznRTErR6upN6WkHSP25Q"
      CLUSTER_ID: "cmznRTErR6upN6WkHSP25Q"
      KAFKA_LISTENERS: "INTERNAL://broker:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://broker:29093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:29092,EXTERNAL://${EC2_PUBLIC_IP}:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-broker-api-versions --bootstrap-server broker:29092 1>/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 30

  # ---------------------------------------------------------------------------
  # Flink JobManager
  # ---------------------------------------------------------------------------
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.jobmanager
    image: flink-python:1.20.0
    pull_policy: build
    container_name: jobmanager
    ports:
      - "8081:8081" # Web UI
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./flink-jobs:/opt/flink/usrlib  # mount your python job here

  # ---------------------------------------------------------------------------
  # Flink TaskManager
  # ---------------------------------------------------------------------------
  taskmanager:
    image: flink-python:1.20.0
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./flink-jobs:/opt/flink/usrlib
